# Site settings
title: Peggy Darlington Design
description: |
  Another fine responsive
  site template freebie
  crafted by [HTML5 UP](http://html5up.net)
owner: Peggy Darlinton Design
first_published: 2016
email: peggydarlingtondesign@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peggydarliingtondesign.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/peggydarlington
  github:
  linkedin-square: https://www.linkedin.com/in/peggy-darlington-bb8ba83
  facebook-official: https://www.facebook.com/peggy.darlington.7
  yelp: https://www.yelp.com/biz/peggy-darlington-design

# Build settings
markdown: kramdown
#sass:
#  style: compressed
